# Generated by Django 6.0.6 on 2026-06-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackReport',
        ),
    ]
